<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataservice.proto

namespace GrpServiceProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GrpServiceProto.ServiceRequest</code>
 */
class ServiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string serviceName = 1;</code>
     */
    protected $serviceName = '';
    /**
     * Generated from protobuf field <code>string methodName = 2;</code>
     */
    protected $methodName = '';
    /**
     * Generated from protobuf field <code>string paramsJson = 3;</code>
     */
    protected $paramsJson = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $serviceName
     *     @type string $methodName
     *     @type string $paramsJson
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dataservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string serviceName = 1;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->serviceName;
    }

    /**
     * Generated from protobuf field <code>string serviceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->serviceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string methodName = 2;</code>
     * @return string
     */
    public function getMethodName()
    {
        return $this->methodName;
    }

    /**
     * Generated from protobuf field <code>string methodName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMethodName($var)
    {
        GPBUtil::checkString($var, True);
        $this->methodName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paramsJson = 3;</code>
     * @return string
     */
    public function getParamsJson()
    {
        return $this->paramsJson;
    }

    /**
     * Generated from protobuf field <code>string paramsJson = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParamsJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->paramsJson = $var;

        return $this;
    }

}

